services:
  - type: web
    name: steal-deals
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4
    envVars:
      - key: DATA_SOURCE
        value: cache
      - key: AMAZON_AFFILIATE_TAG
        value: ftechindia-21
      - key: PYTHON_VERSION
        value: 3.11.9
